### ISSUE TITLE
Performance on GSM8k got 69.9

### ISSUE THREAD

**Issue by allanj** [reasoning-machines/pal#8]
Simply run the script and the accuracy I got is 69.9, but the one reported in the paper is 72.

Wondering what would be the potential difference, notice that the temperature is 0. I guess the might not have a large degree of randomness?

**Comment by madaan** [comment]
Thanks for your interest in our work! Which script did you run? Can you share the output file? We've observed some randomness even with temperature = 0., perhaps due to API calls being routed to different models in the backend.

**Comment by allanj** [comment]
[gsm8k_program_aided_result.json.zip](https://github.com/reasoning-machines/pal/files/10176998/gsm8k_program_aided_result.json.zip)

Sure. I simply try this one: 
https://github.com/reasoning-machines/pal/blob/main/scripts/gsm_eval.py

**Comment by allanj** [comment]
That's an interesting observation. Do you know where I can find more documentation about their backend?

**Comment by madaan** [comment]
Thanks both!

I reproduced the numbers today with [prompt-lib](https://github.com/reasoning-machines/prompt-lib). Here are the commands:


### Running the job

```py
nohup python3 -u prompt-lib/prompt_lib/run_inference.py --task_id gsm_pal --num_prompt_examples -1 --name gsm_pal_code-davinci-002_s1 --model_name code-davinci-002 --max_tokens 600 --max_requests_per_min 16 --seed 0 --num_questions_per_thread 500 --temperature 0.0  --cot_task
```

* The outputs will be stored in `data/logs/gsm_pal/code-davinci-002/temp_0.0/seed_0/k_all/TIMESTAMP/outputs.jsonl`, where TIMESTAMP is an indicator for the time the command was executed. [Here](https://drive.google.com/file/d/1Osc47CevzeRfr_diiMfUZv0iYdmnl5UZ/view?usp=share_link) is the file for your reference.


### Evaluation

```py
python prompt-lib/prompt_lib/eval/eval.py --path "data/logs/gsm_pal/code-davinci-002/temp_0.0/seed_0/k_all/2022-12-08_06-29-38/outputs.jsonl" --type code
```

Output:
```sh
Accuracy: 72.02
```

Going forward, prompt-lib will be our standard method of doing bulk inference. It supports a number of other capabilities, including wandb logging and multiple decodings, so definitely recommend checking it out.



We will investigate reasons for the regression, but I know that Uri was able to get these [cool results](https://github.com/reasoning-machines/pal/pull/5) with current scripts. Also, it is important to note that the numbers in the papers were reported after averaging over three random seeds, so the exact numbers for each run will not exactly match (but should be close).



@zhaoyiran924 We only report numbers for single decoding. The results with multiple samples are [here](https://github.com/reasoning-machines/pal/pull/5) and will be reported in the next version (TLDR: we get 80.4 @40 samples).

**Comment by allanj** [comment]
Thanks a lot for the experiments. Just a quick question before I jump into the new repo: what's actually the difference between the experiments we run and the one you provided? (Except for the max token length.)

**Comment by madaan** [comment]
@allanj No difference ideally! They both use the same prompt, same number of examples, and same model. The regression might be due to error in post-processing the results or the eval script underestimating the results. With that said, we will take another look and report on this issue if we find anything. Just a heads up--our updates might be slow due to EMNLP.

**Comment by urialon** [comment]
Hi all, 
I got 71.4 using this repo, about a week ago.
(I am a co-author of this paper, but I was not involved in the code until a week ago)

@allanj  and @zhaoyiran924  - did you notice any errors in the stout logs? 
I noticed that sometimes the OpenAI API is temporarily unavailable and returns errors that make the results slightly worse.
(We do have an exponential backoff retry mechanism, but if the API is unavailable for long minutes, we sometimes just reach the overall number of retries and just mark that example as incorrectly predicted)

**Comment by allanj** [comment]
Yeah, that could be some randomness. Anyway, I think the variance around 70-72 is reasonable probably due to openAI API.

**Comment by shuyanzhou** [comment]
Hi @allanj, @zhaoyiran924 I also re-run the experiment on `gsm`(1319 examples) with `--max_token 600`. I got an accuracy of `71.26`, similar to @urialon's result. And I agree that the small gaps might due to the randomness in the API calls.

**Comment by allanj** [comment]
Thanks all for your efforts. I will close the issue.
