### ISSUE TITLE
Is GSM-Hard available?

### ISSUE THREAD

**Issue by allanj** [reasoning-machines/pal#9]
Would like to try out this set too. Wondering how I can obtain this set.

**Comment by shuyanzhou** [comment]
Sorry for the delay. The dataset has been added here: https://github.com/reasoning-machines/pal/blob/main/datasets/gsmhardv2.jsonl
You can also access the dataset through huggingface by 
```python
import datasets
gsm_hard = datasets.load_dataset("reasoning-machine/gsm-hard")
```
